
server:
  port: 8081
spring:
  profiles:
    active: query_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri:  http://www.baidu.com
          predicates:
            - After= 2019-07-30T23:59:59.789+08:00[Asia/Shanghai]
  profiles: after_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: header_route
          uri: http://www.baidu.com
          predicates:
            - Header=X-Request-Id, \d+
  profiles: header_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: http://www.baidu.com
          predicates:
            - Cookie=name, chengkun
  profiles: cookie_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://www.baidu.com
          predicates:
            - Host=**.chengkun.com
  profiles: host_route


---
spring:
  cloud:
    gateway:
      routes:
        - id: method_route
          uri: http://www.baidu.com
          predicates:
            - Method=GET
  profiles: method_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://www.baidu.com
          predicates:
            - Path=/foo/{segment}
  profiles: path_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: http://www.baidu.com
          predicates:
            - Query=foo, ba
  profiles: query_route