spring:
  application.name: service-turbine
server:
  port: 8766
turbine:
  aggregator:
    clusterConfig: default   # \u6307\u5B9A\u805A\u5408\u54EA\u4E9B\u96C6\u7FA4\uFF0C\u591A\u4E2A\u4F7F\u7528","\u5206\u5272\uFF0C\u9ED8\u8BA4\u4E3Adefault\u3002\u53EF\u4F7F\u7528http://.../turbine.stream?cluster={clusterConfig\u4E4B\u4E00}\u8BBF\u95EE
  appConfig: service-ribbon,service-feign  # \u914D\u7F6EEureka\u4E2D\u7684serviceId\u5217\u8868\uFF0C\u8868\u660E\u76D1\u63A7\u54EA\u4E9B\u670D\u52A1
  clusterNameExpression: new String("default")
  # 1. clusterNameExpression\u6307\u5B9A\u96C6\u7FA4\u540D\u79F0\uFF0C\u9ED8\u8BA4\u8868\u8FBE\u5F0FappName\uFF1B\u6B64\u65F6\uFF1Aturbine.aggregator.clusterConfig\u9700\u8981\u914D\u7F6E\u60F3\u8981\u76D1\u63A7\u7684\u5E94\u7528\u540D\u79F0
  # 2. \u5F53clusterNameExpression: default\u65F6\uFF0Cturbine.aggregator.clusterConfig\u53EF\u4EE5\u4E0D\u5199\uFF0C\u56E0\u4E3A\u9ED8\u8BA4\u5C31\u662Fdefault
  # 3. \u5F53clusterNameExpression: metadata['cluster']\u65F6\uFF0C\u5047\u8BBE\u60F3\u8981\u76D1\u63A7\u7684\u5E94\u7528\u914D\u7F6E\u4E86eureka.instance.metadata-map.cluster: ABC\uFF0C\u5219\u9700\u8981\u914D\u7F6E\uFF0C\u540C\u65F6turbine.aggregator.clusterConfig: ABC
  combine-host-port: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/