server:
  port: 8769
eureka:
  instance:
    hostname: peer2
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/ #eureka注册地址
spring:
  application:
    name: eureka-server2

